### ISSUE TITLE
aws sync unable to locate credentials

### ISSUE THREAD

**Issue by mxiong2** [nch-igm/snvstory#4]
After building the docker image and running aws sync, I get the following error? Any suggestions to resolve this?

(base) root@CNV:/media/sf_MolecularNGS/Mai/snvstory/snvstory# aws s3 sync s3://igm-public-dropbox/snvstory/resource_dir/ dev/data/resource_dir/

fatal error: Unable to locate credentials

(base) root@CNV:/media/sf_MolecularNGS/Mai/snvstory/snvstory#

**Comment by andreirajkovic** [comment]
aws s3 sync s3://igm-public-dropbox/snvstory/resource_dir . --no-sign-request

**Comment by andreirajkovic** [comment]
@mxiong2 did that solve the issue?

**Comment by mxiong2** [comment]
@andreirajkovic , download is working! Thank you.
