### ISSUE TITLE
Docker images available?

### ISSUE THREAD

**Issue by lcoombe** [nch-igm/snvstory#7]
Hello,

Do you have any pre-built docker images available? I do not have root access on my machines, so cannot run docker, but can run built docker images using singularity. 

Alternatively, could SNVstory be installed using a virtual environment (following the dependencies in the Dockerfile)?

Thanks!
Lauren

**Comment by andreirajkovic** [comment]
Hi @lcoombe you can find the docker image for this version here: docker pull heritagehelix/snvstory:3.0.0
And while I personally haven't I'm pretty sure you could build SNVstory using a virtual environment. There would be some tricks to making sure your environment played nice with the correct numba version; we run into lots of issues there.

Let me know if that Docker worked for you or if you have any other questions.

**Comment by lcoombe** [comment]
I'll give that docker image a try - thank you so much!
