### ISSUE TITLE
SGDP_continental prediction fails

### ISSUE THREAD

**Issue by SigveLan** [nch-igm/snvstory#8]
Hi, I'm getting this error every time the SGDP_continental step is reached. 

```
SGDP_continental
Check ordered length of SNPs. "None of [Index(['chr1_69270_A_G', 'chr1_69511_A_G', 'chr1_69761_A_T', 'chr1_69897_T_C',\n       'chr1_930314_C_T', 'chr1_939285_G_A', 'chr1_939354_C_T',\n       'chr1_939398_GCCTCCCCAGCCACGGTGAGGACCCACCCTGGCATGATCCCCCTCATCA_G',\n       'chr1_941282_C_A', 'chr1_942930_T_C',\n       ...\n       'chr22_50627172_G_A', 'chr22_50627388_G_A', 'chr22_50679152_T_C',\n       'chr22_50714943_G_A', 'chr22_50720830_C_T', 'chr22_50744827_A_G',\n       'chr22_50744993_C_T', 'chr22_50745030_A_C', 'chr22_50745036_A_C',\n       'chr22_50776695_C_T'],\n      dtype='object', length=97995)] are in the [columns]"
Cannot coerce data. Check sparse matrix: None
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/Ancestry/igm_churchill_ancestry/__main__.py", line 4, in <module>
    run_ancestry()
  File "/opt/Ancestry/igm_churchill_ancestry/cli.py", line 182, in run_ancestry
    ofn=ofn)
  File "/opt/Ancestry/igm_churchill_ancestry/pipelines/ancestry_prediction.py", line 111, in run_ancestry_pipeline
    yprob, ylabel = predict_ancestry(s_matrix, ml_dir=ml_dir, n_classes=n_classes, model_type='svm')
TypeError: cannot unpack non-iterable NoneType object
```
I've tried different vcfs, including the one posted in the "best practice VCF input" issue. I've also tried building with docker compose and using the heritagehelix/snvstory:3.0.0 docker image, same error. All the preceding predictions appear to run just fine. Any ideas as to what might be causing this?

Not sure if it helps, but the log files always end with these three lines:
```
2024-03-05 17:06:10,180:DEBUG:==== SSA block rewrite pass on 511
2024-03-05 17:06:10,180:DEBUG:Running <numba.core.ssa._FixSSAVars object at 0x7fdaf4acee90>
2024-03-05 17:06:10,180:DEBUG:on stmt: jump 154
```

**Comment by timchu90** [comment]
ran into this same issue. seems like the code is trying to grab the sgdp var_id.json but is incorrectly reading in some other jsons. renaming the resource files:
```
sgdp/continental/matrix_attributes/sgdp_country.json
sgdp/continental/matrix_attributes/sgdp_sample.json
```
to something that does not end in .json got past that error for me.
that said, i still haven't been able to run the code to completion

**Comment by andreirajkovic** [comment]
@SigveLan could you provide the docker command you used to run snvstory?

**Comment by andreirajkovic** [comment]
Also could you verify that your sgdp/continental/matrix_attributes looks like this:
![image](https://github.com/nch-igm/snvstory/assets/34891295/926bfb71-18fe-4526-9fd5-27f381b099cc)

**Comment by SigveLan** [comment]
Yes, so this is the command I've used:

```
docker run -it --rm -v $PWD:/data heritagehelix/snvstory:3.0.0 \
	--resource /data/resource_dir/ \
	--genome-ver 38 \
	--mode WES \
	--output-dir /data/output/ \
	--path /data/sample_1.vcf.gz
```

As for the files they are exactly the same as you posted.

**Comment by andreirajkovic** [comment]
Your command looks good to me, when I run it locally it works w/o any issues. I'm going to try and add some tests to the code base this week and hopefully you'll be able to run them and we'll be able to extract more diagnostics from that. By the way what operating system are you using?

**Comment by lcoombe** [comment]
Hello! Just adding that I'm seeing the same error on my side when running a test with the provided `HG00096_extracted.vcf.gz` file.

I'm using singularity with the provided docker image with this command:
```
singularity exec -B $PWD:$PWD,/projects/btl/lcoombe/bin/snvstory/3.0.0/dev/data/resource_dir/:$PWD/dev/data/resource_dir \
   --env PYTHONPATH=/opt/Ancestry/:$PYTHONPATH --env TMP_DIR=$PWD/tmp \
    /projects/btl/lcoombe/bin/snvstory/3.0.0/snvstory-3.0.0.sif python3 -m igm_churchill_ancestry  \
   --path HG00096_extracted.vcf.gz --resource $PWD/dev/data/resource_dir --genome-ver 38  \
   --mode WES --output-dir /snv_out
```

The `matrix_attributes` resource dir also looks as expected:
```
(btl) [lcoombe@hpce706 HG00096_test]$ ls /projects/btl/lcoombe/bin/snvstory/3.0.0/dev/data/resource_dir/sgdp/continental/matrix_attributes/
ordered_sgdp.intersect_exome.sparse_matrix.var_ids.txt  sgdp.intersect_exome.sparse_matrix.var_ids.json  SGDP_umap_attributes.csv
sgdp_country.json                                       sgdp_sample.json
```

**Comment by andreirajkovic** [comment]
I think I found the issue; @timchu90  was barking up the right tree. The problem has to do with the matrix_attributes folder having multiple JSONs. On my local machine (and I guess the machine where we developed this on) sgdp.intersect_exome.sparse_matrix.var_ids.json loaded first, whereas when I run the singularity command sgdp_country.json is what loads first, which is not what we want. 

This is a silly mistake on our end and a simple fix. I'll try and put a fix in this weekend.

**Comment by andreirajkovic** [comment]
@SigveLan @lcoombe and @timchu90 I've put out a PR for this fix and pushed a new version of the docker heritagehelix/snvstory:3.0.1 Feel free to use the new docker version and I'll merge the PR once I have confirmation from one of you that it works, or if I get a around to running it on the server with singularity.

**Comment by SigveLan** [comment]
Works for me!

**Comment by lcoombe** [comment]
Thanks for the quick fix! I was able to run the new image using singularity successfully on the `HG00096_extracted.vcf.gz` test data 👍
